### ISSUE TITLE
toList return empty list

### ISSUE THREAD

**Issue by ram535** [bsutton/dshell#49]
When running:

```
var version = 'dart --version'.toList();
print(version);
```
I get an empty list. I was expecting to get a list<String> with the output of the command.

**Comment by bsutton** [comment]
The problem is that 'toList' only captures output written to stdout.
dart --version is writting to stderr so toList ignores its output.

We could add an option so that it captures stderr or make it so it always captures both.
Thoughts?

In  1.1.1-dev.3 I have exposed a class called DartSDK which provides details about the sdk such as its paths and version.

**Comment by bsutton** [comment]
I'm inclined to change toList to capture everything by default as this was clearly your expectation. We could may add an option to exclude stderr but I'm inclined to wait and see what other peoples experience before adding that option.

**Comment by bsutton** [comment]
I've also added a new method 'firstLine' which will simply return the first line rather than the entire list.

**Comment by ram535** [comment]
Now that you explain it, it make sense. As a beginner, I don't understand why you would put the output of your command to stderr when it is not an error. If a lot of commands do that, then I think by default should be to capture both.
