### ISSUE TITLE
Being able to run strings that include pipe operator

### ISSUE THREAD

**Issue by ram535** [bsutton/dshell#69]
Why is not possible to do something like this?

```
'ls | head -3'.run;
```

It is a little convenience to be able to do that.

**Comment by bsutton** [comment]
Your problem is that the '.run' method expects the string to contain a single application to run.

You have passed the .run method what is essentially as bash command string.

The .run method doesn't start bash so it doesn't know what to do with it.

The way to achieve the desired outcome is to use the dshell pipe operator:

('ls' | 'head -3').run;

The parentheses are necessary as the . operator in the '.run' has a higher precedence than the | operator and we need the | operator to execute first.
